[colors]
ansi = [
    '#1e1e2e',
    '#f38ba8',
    '#a6e3a1',
    '#f9e2af',
    '#89b4fa',
    '#cba6f7',
    '#74c7ec',
    '#cdd6f4',
]
brights = [
    '#313244',
    '#eba0ac',
    '#94e2d5',
    '#fab387',
    '#b4befe',
    '#f5c2e7',
    '#89dceb',
    '#cdd6f4',
]
cursor_bg = '#bac2de'
cursor_border = '#bac2de'
cursor_fg = '#ffffff'
background = '#111827'
foreground = '#cdd6f4'
selection_bg = '#313244'
selection_fg = '#cdd6f4'

[colors.indexed]

[metadata]
name = 'Catppuccin'
